### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Butochnikov** [stephancasas/snowblade-demo-app#1]
I try `npm run build` and got error:
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! presto-demo-app@1.0.0 transpile:dom: `presto -c presto.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the presto-demo-app@1.0.0 transpile:dom script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by stephancasas** [comment]
Thank you for reporting this. Can you please share your NPM, Node, and OS version?

**Comment by Butochnikov** [comment]
OS  Ubuntu 18.04.5 LTS
node v12.18
npm 6.14.11

**Comment by stephancasas** [comment]
I'll load a VM tonight and run some tests. Thank you for the extra details!

**Comment by stephancasas** [comment]
Hello,

This issue was related to an incorrect target set on the TypeScript compiler for the dist version of Presto. However, it also afforded an opportunity to drop `@babel/core` as the transpiler used to read `presto.config.js` and any user-defined property pipe functions. That's resulted in an overall smaller package footprint and faster install/download time, so thanks for that!

I've tested this on my Ubuntu instance with success using Presto v1.0.31. The demo app `package.json` has been updated to reflect this, so you can either uninstall/reinstall Presto in your existing clone, or just grab the updated demo app again.

Please let me know if it works on your end.

Thanks!

**Comment by Butochnikov** [comment]
![image](https://user-images.githubusercontent.com/4212297/107972459-ee774880-6fc4-11eb-91f1-f92cf7e227f2.png)

Thanks!

**Comment by Butochnikov** [comment]
@stephancasas 
only this error

```bash
./dist/es2020/app.js → ./dist/public/app.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/alpinejs/dist/alpine.js
3:   typeof define === 'function' && define.amd ? define(factory) :
4:   (global = global || self, global.Alpine = factory());
5: }(this, (function () { 'use strict';
     ^
6:
7:   function _defineProperty(obj, key, value) {
created ./dist/public/app.js in 2s
```

but everything works

**Comment by stephancasas** [comment]
Yes, the Alpine logic isn't written in a way that Rollup likes, but it works when compiled and executed in the browser. I'm still experimenting with different ways to fractionalize that part of the development process, and haven't really landed on something I like as of yet.
